name: CI

on:
  push:
    branches: [ 1.18.2 ]
  pull_request:
    branches: [ 1.18.2 ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution : 'adopt'
    - name : grant permission for gradlew
      run : chmod +x gradlew
    - name : build
      run : ./gradlew build
    - name : upload
      uses : actions/upload-artifact@v2
      with :
        name : Industrimania
        path : ${{github.workspace}}/build/libs/*
